export default{
    "women": [
        "Bluzka va ko’ylak",
        "Shimlar",
        "Ustki kiyimlar ",
        "Djinsi kurtka",
        "Terili kurtka",
        "Palto",
        "Parki",
        "Plash va trench",
        "Puxli va qishki kurtkalar",
        "Djemfer va kardiganlar",
        "Jinsi ",
        "Ayollar pijjamasi",
        "Jiletlar",
        "Kombinizonlar",
        "Shortikli kombinizonlar",
        "Kostyumlar",
        "Plyaj kiyimlari va kupalniklar",
        "Ichki kiyimlar",
        "Ayollar paypoqlari va ipli mahsulotlar",
        "Pidjaklar",
        "Ko’ylaklar",
        "Qalin kiyimlar va kurtkalar",
        "Futbolkalar",
        "Shortiklar",
        "Yubkalar",
        "Soch turmagi uchun aksessuar",
        "Bosh qismi uchun aksessuar",
        "Ochkilar",
        "Qo’lqoplar ",
        "Kamarlar",
        "Sharflar",
        "Ro’mollar"
    ],
    "man": [
        "Ko’ylaklar ",
        "Shimlar",
        "Ustki kiyimlar ",
        "Djinsi kurtka",
        "Terili kurtka",
        "Palto",
        "Parki",
        "Plash va trench",
        "Puxli va qishki kurtkalar",
        "Djemfer va kardiganlar",
        "Jinsi ",
        "erkaklar pijjamasi",
        "Jiletlar",
        "Kombinizonlar",
        "Shortikli kombinizonlar",
        "Kostyumlar",
        "Plyaj kiyimlari",
        "Ichki kiyimlar",
        "Erkaklar  paypoqlari va ipli mahsulotlar",
        "Pidjaklar",
        "Qalin kiyimlar va kurtkalar",
        "Futbolkalar",
        "Shortiklar",
        "Yubkalar",
        "Galstuk va ro’molchalar",
        "Bosh qismi uchun aksessuar",
        "Ochkilar",
        "Qo’lqoplar ",
        "Kamarlar",
        "Sharflar"
        
    ],
    "mobile": [
        "Xiaomi",
        "Apple",
        "Samsung",
        "Huawei",
        "Meizu",
        "Artel",
        "Nokia",
        "Smart soatlar",
        "Smart brasletlar",
        "Quloqchin va garnituralar",
        "Simli",
        "Simsiz(bluetooth)",
        "Apple airpods",
        "Display",
        "Akkumulyatorlar",
        "Qolgan qismlar",
        "Smartfonlar uchun ustki g’ilof(chexollar)",
        "Xiaomi",
        "Apple",
        " Samsung",
        " Huawei",
        "Meizu",
        "Artel",
        " Nokia",
        "Himoya oynalari va plyonkalari",
        "Kabellar",
        "Quvvatlagichlar",
        "Tashqi akkumulyatorlar",
        "Ushlagichlar",
        "Tashqi xotira vositalari"
    ],
    "pc": [
        "Noutbuklar, kompyuter jamlanmasi, monitorlar",
        "Noutbuklar",
        "Apple noutbuklari",
        "Tizim bloklari",
        "Monitorlar",
        "Planshetlar",
        "Elektron kitoblar",
        "Mini shaxsiy kompyuter",
        "Komplekt jihozlar",
        "Protsessorlar",
        "Videoxotiralar",
        "Ona platalar",
        "Xotira modullari",
        "Sovutish tizimi",
        "Qattiq disklar, SSD",
        "Quvvat bloki",
        "Tashqi korpus",
        "Aksessuarlar",
        "Klaviatura va sichqoncha",
        "Noutbuklar uchun Sumka, chexol",
        "Kompyuter musiqiy kolonkalari",
        "Quloqchinlar va garnituralar",
        "O’yin aksessuarlari",
        "Orgtexnika",
        "Printerlar, MFU",
        "3D printerlar",
        "Chiqim materiallari",
        "Saqlash vositalari",
        "USB fleshkalar",
        "Xotira kartalari",
        "Tashqi qattiq disklar",
        "Routerlar",
        "3G va 4G modemlar",
        "O’yin uchun noutbuklar",
        "O’yin kompyuterlari",
        "O’yin uchun monitorlar",
        "O’yin uchun sichqoncha va klaviaturalar",
        "O’yin uchun maxsus videoxotiralar",
        "O’yinchilar uchun kreslo va stollar"
    ],
    "electric": [
        "Quloqchin va garniture",
        "Portativ kolonkalar",
        "MP3 playerlar",
        "Electron kitoblar",
        "VR/AR qurilmalar",
        "Televizor va videotexnika",
        "Televizorlar",
        "Proektorlar",
        "TV pristavka va mediaplayerlar",
        "TV uchun kronshteynlar",
        "Pultlar",
        "Onlayn kinoteatrlar",
        "O’yin va konsolkalar",
        "O’yin konsollari",
        "Portativ o’yin konsollari",
        "O’yinlar(disk va katridjlar)",
        "O’yinlar va raqamli content",
        "Geympadlar",
        "Audiotizimlar",
        "Kompyuter uchun",
        "TV uchun Saundbar",
        "Hi-Fi audiotexnika",
        "Uy kinoteatri",
        "Aqlli uy",
        "Aqlli uy uchun qurilmalar",
        "Aqlli kolonkalar",
        "Elektronika uchun aksessuarlar",
        "Kabel va adapterlar",
        "Batareyka va akkumulyatorlar",
        "Foto va videotexnika",
        "Kvadrokopter va dronlar",
        "Ekshn kameralar",
        "Fotostudia",
        "Foto va video qurilmalar uchun aksessuarlar",
        "Videoregistratorlar",
        "Xavfsizlik va himoya",
        "Videokuzatuv moslamalari",
        "Videokuzatuv xizmati"
        
    ],
    "jewelery": [
        "Sirg’alar",
        "Uzuklar",
        "Brasletlar",
        "Yuvelir komplektlar",
        "Unashtiruv uzuklari",
        "Bo’yin sipochkasi",
        "Sirg’alar",
        "Uzuklar",
        " Brasletlar",
        " Yuvelir komplektlar",
        " Unashtiruv uzuklari",
        "Bo’yin sipochkasi",
        "Sirg’alar",
        "Uzuklar",
        " Brasletlar",
        " Yuvelir komplektlar",
        " Unashtiruv uzuklari",
        " Bo’yin sipochkasi",
        "Erkaklar soati",
        "Mexanik soatlar",
        "Kvarts soatlar",
        "Sport uchun soatlar",
        "Raqamli soatlar",
        "Ayollar soati",
        "Soat brasletlar",
        "Juft soatlar",
        "Bolalar soati",
        "Soatlar uchun aksessuarlar"
        
    ],
    "home": [
        "Yotoq mebeli",
        "Yotoqxona kiyim shkafi",
        "Tumbochka",
        "Komod",
        "Komplekt",
        "Stol stul",
        "Stul",
        "Stol",
        "Xontaxta",
        "Servis mebeli",
        "Komplekt",
        "Stol stul",
        "Stol",
        "Stul",
        "Oshxona shkafi",
        "Komplekt",
        "Xontaxta",
        "Eshik oldi mebeli",
        "Devorga osiladigan mebel",
        "Oyoq kiyimlar uchun mebel",
        "Ust kiyimlar uchun mebel",
        "Komplekt",
        "Bolalar mebeli",
        "Kiyim uchun mebel",
        "Ust kiyimlar uchun mebel",
        "Komplekt",
        "sandiqlar"
        
    ],
    "bag": [
        "Ayollar sumkalari",
        "Talabalar uchun sumka",
        "Talabalar uchun ryukzak",
        "O’quvchilar sumkasi",
        "O’quvchilar ryukzaki",
        "Sport uchun sumka",
        "Sport uchun ryukzak",
        "Sayohat uchun sumka",
        "Sayohat uchun ryukzak",
        "Sayohat uchun chamadon",
        "Ayollar oyoq kiyimlari",
        "Talabalar uchun oyoq kiyimlar(klassik)",
        "Talabalar uchun kiyimlar(kundalik)",
        "O’quvchilar oyoq kiyimlari(klassik)",
        "O’quvchilar oyoq kiyimlari(kundalik)",
        "Sport uchun oyoq kiyimlar(maxsus)",
        "Sport uchun oyoq kiyimlar(kundalik)",
        "Sayohat uchun oyoq kiyimlar(klassik)",
        "Sayohat uchun oyoq kiyimlar(maxsus)"
    ],
    "toy": [
        "Yumshoq o’yinchoqlar",
        "Qo’g’irchoqlar",
        "Komplekt",
        "Lego o’yinlari",
        "Rezina o’yinchoqlar",
        "Ekologik o’yinchoqlar",
        "Taxtali o’yinchoqlar"
    ],
    "stool": [
        "Ruchkalar",
        "Daftarlar(hoshiyali)",
        "Daftarlar(katak)",
        "Hisob varaqalari",
        "Kitoblar",
        "Rangli qog’ozlar",
        "Flamaster",
        "Marker",
        "Mel",
        "Ofis uchun maxsus ",
        "Qalamlar",
        "Rasm chizish uchun",
        "Maktabgacha ta’lim uchun",
        "Maktab o’quv qurollari"
        
    ],
    "build": [
        "Shkutakurka mahsulotlari",
        "Plastic mahsulotlar",
        "Bo’yoq mahsulotlari",
        "Taxtali mahsulotlar",
        "Temir mahsulotlar"
    ],
    "food": [
        "Un",
        "Non",
        "Bulochka",
        "Tayyor va yarim tayyor Xamir mahsulotlari ",
        "Piroglar",
        "Tortlar ",
        "Sut",
        "Quruq sut",
        "Qatiq va qatiq mahsulotlari",
        "Pishloq va brinza",
        "Qiyma",
        "Go’sht",
        "Yarim tayyor kabob uchun go’sht",
        "Tovuq go’shti",
        "Kolbasa mahsulotlar",
        "Sosiskalar"
        
    ],
    "medicine": [
        "Maxsus dorilar(topilishi qiyin bo’lgan maxsus dorilar, astmatik, qand kasalligi borlar uchun)",
        "Yurak uchun",
        "Jigar uchun",
        "Oshqozon uchun",
        "Umumiy foydalanish uchun",
        "Balsam va mazlar",
        "Tabiiy dorilar",
        "Eritmalar",
        "Siroplar",
        "Nogironlar aravachasi",
        "Nogironlar uchun qo’ltiqoyoq",
        "Maxsus protez tana a’zolari",
        "Umurtqa uchun",
        "Bo’yin uchun",
        "Maxsus ortopedik oyoq kiyim va qurilmalar"
        
    ],
    "backyard": [
        "Tog’oralar",
        "Chelaklar",
        "Ketmon",
        "Belkurak",
        "O’roq",
        "Maxsus texnika",
        "Bolgarka",
        "Drel",
        "Panshaxa",
        "Tomorqa uchun qurilmalar",
        "Tomchilatib sug’orish texnologiyalar",
        "Tomorqa mahsulotlari uchun o’g’itlar"
    ],
    "spare": [
        "Avtooynalar",
        "Signalizatsiya",
        "aksessuarlar"
    ],
    "material": [
        "Kiyim uchun materiallar",
        "Sarpo materiallari",
        "Ko’rpa to’shak materiali",
        "Bichuv uchun maxsus materiallar",
        "Tikuvchilik uchun maxsus qurilmalar"
    ],
    "additional": [
        "Sarpo uchun sandiq",
        "Sarpo uchun ko’rpa to’shaklar",
        "Sarpo uchun yostiqlar",
        "Sarpo uchun dasturxon va sochiqlar",
        "Sarpo uchun idish tovoqlar"
    ],
    "dish": [
         "Mehmon kutish uchun", 
         "Doimiy foydalanish uchun",
         "Komplekt idish tovoqlar",
         "Oshxona idish tovoqlari"
]
}