import LocalizedStrings from 'react-native-localization';

export default strings = new LocalizedStrings({
    
  ru: {
      search:"поиск",
      categoryies:"категоры",
      all:"все",
      editPr:"Редактировать",
      shippingAd:"Адресс доставки",
      wishlist:"Cписок желаний",
      orderH:"История заказов",
      currency:"сум",
      settings:"Настройки",
      updateSetting:"Обновить настройки",
      note:"Уведомление",
      popup:"Всплывающие окна",
      notetitle:"Получайте уведомления о последних предложениях и обновлениях магазина",
      poptitle:"Отключить все всплывающие окна и рекламу от сторонних поставщиков",
      orderhtitle:"Сохраняйте историю заказов в приложении, если не удалите ее вручную",
      total:"Итоги",
      subtotal:"Промежуточный итог",
      shipping:"Доставка",
      enterVo:"Введите код ваучера",
      apply:"применять",
      checkout:"следующий",
      next:"следующий",
      back:"назад",
      city:"город",
      billadd:"Платежный адрес такой же, как и для доставки",
      street:"улица",
      state:"штат",
      country:"страна",
      change:"изменить",
      pay:"оплачивать",
      orderA:"Заказ принят",
      youOn:"Номер вашего заказа",
      track:"Отследить заказ",
      summary:"Все",
      hello:"привет",
      women:"Женская одежда",
      accessories:"аксессуары",
      tshirt:"Футболка",
      shoes:"обувь",
      coat:"Пальто",
      home:"Главное",
      cart:"Корзина",
      account:"Профиль",
      logout:"выйти",


  },
    uz:{
      search:"qidirish",
      categoryies:"kategoriyalar",
      all:"barchasi",
      currency:"so'm",
      settings:"Sozlamalar",
      updateSetting:"Sozlamalarni yangilash",
      editPr:"Profilni sozlash",
      shippingAd:"Yetkazish manzil",
      wishlist:"Yoqtirganlar",
      orderH:"Buyurtmalar",
      note:"Xabarnoma",
      popup:"Qalqib chiquvchi oynalar",
      notetitle:"Eng so'nggi takliflar va do'kon yangilanishlari haqida xabardor bo'ling",
      poptitle:"Reklamalarni o'chirish",
      orderhtitle:"Buyurtmalaringiz tarixini ilovada saqlang",
      total:"Jami",
      subtotal:"Tovar narxi",
      shipping:"Yetkazib berish",
      enterVo:"Voucher kodini kiriting",
      apply:"kiritish",
      checkout:"keyingisi",
      next:"keyingisi",
      back:"orqaga",
      city:"city",
      billadd:"To'lov manzili etkazib berish bilan bir xil",
      street:"ko'cha",
      state:"davlat",
      country:"mamlakat",
      change:"o'zgartirish",
      pay:"to'lash",
      orderA:"Buyurtma qabul qilindi",
      youOn:"Buyurtma raqamingiz",
      track:"Buyurtmani ko'rish",
      summary:"Barchasi",
      hello:"salom",
      women:"ayollar kiyimi",
      accessories:"aksessuarlar",
      tshirt:"futbolka",
      shoes:"oyoq kiyim",
      coat:"palto",
      home:"Asosiy",
      cart:"Cart",
      account:"Profil",
      logout:"chiqish"

    },
    // en:{
    //     orderH:"Order history",
    //     categoryies:"categories",
    //     editPr:"Edit profile",
    //     notetitle:"Recive notifications on latest offers and store updates",
    //     poptitle:"Disable all popups and adverts from third partyy vendors",
    //     orderhtitle:"Keep your order history on the app unless manually removed",
    //     search:"search",
    //     note:"Notification",
    //     updateSetting:"update settings",
    //     currency:"sum",
    //     popup:"Pop ups",
    //     settings:"Settings",
    //     all:"all",
    //     shippingAd:"Shipping address",
    //     wishlist:"wishlist",
    //     total:"Totals",
    //     subtotal:"Sub total",
    //     shipping:"Shipping",
    //     enterVo:"Enter voucher code",
    //     apply:"apply",
    //     checkout:"checkout",
    //     next:"next",
    //     back:"back",
    //     city:"city",
    //     billadd:"Billing address is same as shipping",
    //     street:"street",
    //     state:"state",
    //     country:"country",
    //     change:"change",
    //     pay:"pay",
    //     orderA:"Order accepted",
    //     youOn:"Your order number",
    //     track:"track order",
    //     summary:"summary",
    //     hello:"hello",
    //     home:"Home",
    //     cart:"Cart",
    //     account:"Account",
    //     women:"ayollar kiyimi",
    //     accessories:"aksessuarlar",
    //     tshirt:"futbolka",
    //     shoes:"oyoq kiyim",
    //     coat:"palto",
    //     logout:"logout" 
    //   },
   });

